### ISSUE TITLE
Problems with `data_store.search_data` with param `data_type`

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-cci#54]
There is an issue with querying datasets by their data_type. With the store implementation the data_type is set to e.g. 'dataset'. 
To reproduce:
```
from cate.core import DATA_STORE_POOL
cci_store='cci-store'

data_store = DATA_STORE_POOL.get_store(cci_store)
display(data_store.get_search_params_schema())

```
This query used to work
`seaiceqry=data_store.search_data(ecv='SEAICE', data_type="SICONC")`

now it leads to an `ValueError: unknown data type 'SICONC'`

When taking a look at the metadata of a dataset queried with: 

`seaiceqry=data_store.search_data(ecv='SEAICE')`

you can see that the attrs of the dataset also include `data_type="SICONC"`

![image](https://user-images.githubusercontent.com/23457217/139879230-6563a853-5ef0-48a2-8251-ee5fac06cb8a.png)

it would be good, if one could also query attributes of a dataset.

**Comment by TonioF** [comment]
It is not possible anymore to include this as a search parameter, as the parameter 'data_type' is now used by the store framework. It is possible to rename this one to 'type_of_data', though.
